name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          bundler-cache: true
          ruby-version: 3.0.1
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Setup
        run: |
          bin/rake db:create
          bin/rake db:migrate
          bin/rake db:migrate APP_ENV=test
      - name: Add seeds
        run: ruby bin/seed.rb
      - name: Run tests
        run: bin/rspec spec
